site_name: tears
site_description:
site_url:
theme:
    name: material
    custom_dir: docs/overrides
    features:
        - navigation.indexes
        - navigation.path
        - navigation.indexes
        - navigation.footer
        - toc.follow
        - search.suggest
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          accent: pink
          toggle:
              icon: material/weather-night
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: teal
          accent: pink
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode

markdown_extensions:
    - def_list
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
    - search
extra_css:
    - stylesheets/doxide.css
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
